version: "3.8"
services:
  api:
    image: "budhiarta/capstone-15:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=capstone
      - CLOUDINARY_URL=cloudinary://864167348632296:BWJBloyOSCLs6Zfi9pPxvDQ_TlY@dwvq529jy 
    ports:
      - "8000:8000"
    networks:
      - db_main
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstone
    ports:
      - "3306:3306"
    networks:
      - db_main
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  db_main:
    driver: bridge